version: '3.8'

services:
    selenium-chrome:
        image: ${SELENIUM_IMAGE}
        ports:
            - 4444:4444
        networks: 
            - bridge
        healthcheck:
            test: /opt/bin/check-grid.sh --host 0.0.0.0 --port 4444
            interval: 15s
            timeout: 30s
            retries: 10

    farmer:
        build: .
        networks: 
            - bridge
        depends_on:
            selenium-chrome:
                condition: service_healthy
        environment: 
            - EMAIL=${MS_CREDS_USR}
            - PASSWORD=${MS_CREDS_PSW}
            - WEBDRIVER_ADDR=http://selenium-chrome:4444/wd/hub

networks:
    bridge:
        driver: bridge