version: '3.8'

services:
    selenium-chrome:
        image: ${SELENIUM_IMAGE}
        ports:
            - 4444:4444
        networks: 
            - bridge

    farmer:
        build: .
        networks: 
            - bridge
        depends_on:
            - selenium-chrome
        environment: 
            - EMAIL=${MS_CREDS_USR}
            - PASSWORD=${MS_CREDS_PSW}
            - WEBDRIVER_ADDR=http://selenium-chrome:4444/wd/hub

networks:
    bridge:
        driver: bridge